// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_wb78vO4d7VfjfV4vrSZJvlwMu2B4nuc',
    appId: '1:382849249806:web:bc365c5bb4cbdf4619025f',
    messagingSenderId: '382849249806',
    projectId: 'cocktail-party-7c7b8',
    authDomain: 'cocktail-party-7c7b8.firebaseapp.com',
    storageBucket: 'cocktail-party-7c7b8.appspot.com',
    measurementId: 'G-935ZGDW8RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvTpum9avMsdiKev7GkNIThi3ka4LE_jQ',
    appId: '1:382849249806:android:56a2e727944f9b2119025f',
    messagingSenderId: '382849249806',
    projectId: 'cocktail-party-7c7b8',
    storageBucket: 'cocktail-party-7c7b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8c6sojY91GPRxo-g4wUj-hCyXJzp_mLM',
    appId: '1:382849249806:ios:f7c8c44a14639e4119025f',
    messagingSenderId: '382849249806',
    projectId: 'cocktail-party-7c7b8',
    storageBucket: 'cocktail-party-7c7b8.appspot.com',
    iosClientId: '382849249806-81i603r17ss4d444ef8ghlib85u4ofom.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocktalez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8c6sojY91GPRxo-g4wUj-hCyXJzp_mLM',
    appId: '1:382849249806:ios:f7c8c44a14639e4119025f',
    messagingSenderId: '382849249806',
    projectId: 'cocktail-party-7c7b8',
    storageBucket: 'cocktail-party-7c7b8.appspot.com',
    iosClientId: '382849249806-81i603r17ss4d444ef8ghlib85u4ofom.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocktalez',
  );
}
